from enum import IntEnum
 
class WinEvent(IntEnum):
    """WinEvent constant values. For more details see: https://learn.microsoft.com/en-us/windows/win32/winauto/event-constants"""

    # Overall min/max range
    EVENT_MIN                      = 0x00000001  # Lowest possible event value
    EVENT_MAX                      = 0x7FFFFFFF  # Highest possible event value

    # Accessibility Interoperability Alliance (AIA) range
    EVENT_AIA_START                = 0xA000      # Start of AIA-defined events
    EVENT_AIA_END                  = 0xAFFF      # End of AIA-defined events

    # OEM-defined range
    EVENT_OEM_DEFINED_START        = 0x0101      # Start of OEM-reserved events
    EVENT_OEM_DEFINED_END          = 0x01FF      # End of OEM-reserved events

    # UI Automation ranges
    EVENT_UIA_EVENTID_START        = 0x4E00      # Start of UIA event IDs
    EVENT_UIA_EVENTID_END          = 0x4EFF      # End of UIA event IDs
    EVENT_UIA_PROPID_START         = 0x7500      # Start of UIA property-changed IDs
    EVENT_UIA_PROPID_END           = 0x75FF      # End of UIA property-changed IDs

    # System events
    EVENT_SYSTEM_SOUND             = 0x0001      # A sound has been played
    EVENT_SYSTEM_ALERT             = 0x0002      # An alert has been generated
    EVENT_SYSTEM_FOREGROUND        = 0x0003      # Foreground window changed
    EVENT_SYSTEM_MENUSTART         = 0x0004      # Menu bar item selected
    EVENT_SYSTEM_MENUEND           = 0x0005      # Menu closed
    EVENT_SYSTEM_MENUPOPUPSTART    = 0x0006      # Pop-up menu opened
    EVENT_SYSTEM_MENUPOPUPEND      = 0x0007      # Pop-up menu closed
    EVENT_SYSTEM_CAPTURESTART      = 0x0008      # Window received mouse capture
    EVENT_SYSTEM_CAPTUREEND        = 0x0009      # Window lost mouse capture
    EVENT_SYSTEM_MOVESIZESTART     = 0x000A      # Window moving/resizing started
    EVENT_SYSTEM_MOVESIZEEND       = 0x000B      # Window moving/resizing ended
    EVENT_SYSTEM_CONTEXTHELPSTART  = 0x000C      # Entered context-sensitive Help mode
    EVENT_SYSTEM_CONTEXTHELPEND    = 0x000D      # Exited context-sensitive Help mode
    EVENT_SYSTEM_DRAGDROPSTART     = 0x000E      # Entered drag-and-drop mode
    EVENT_SYSTEM_DRAGDROPEND       = 0x000F      # Exiting drag-and-drop mode
    EVENT_SYSTEM_DIALOGSTART       = 0x0010      # Dialog box shown
    EVENT_SYSTEM_DIALOGEND         = 0x0011      # Dialog box closed
    EVENT_SYSTEM_SCROLLINGSTART    = 0x0012      # Scroll started on a scroll bar
    EVENT_SYSTEM_SCROLLINGEND      = 0x0013      # Scroll ended on a scroll bar
    EVENT_SYSTEM_SWITCHSTART       = 0x0014      # ALT+TAB pressed (switch start)
    EVENT_SYSTEM_SWITCHEND         = 0x0015      # ALT+TAB released (switch end)
    EVENT_SYSTEM_MINIMIZESTART     = 0x0016      # Window about to be minimized
    EVENT_SYSTEM_MINIMIZEEND       = 0x0017      # Window about to be restored
    EVENT_SYSTEM_DESKTOPSWITCH     = 0x0020      # Desktop switched

    # Object events
    EVENT_OBJECT_CREATE            = 0x8000      # An object has been created
    EVENT_OBJECT_DESTROY           = 0x8001      # An object has been destroyed
    EVENT_OBJECT_SHOW              = 0x8002      # A hidden object is shown
    EVENT_OBJECT_HIDE              = 0x8003      # An object is hidden
    EVENT_OBJECT_REORDER           = 0x8004      # Container's children reordered
    EVENT_OBJECT_FOCUS             = 0x8005      # Object received keyboard focus
    EVENT_OBJECT_SELECTION         = 0x8006      # Selection changed in container
    EVENT_OBJECT_SELECTIONADD      = 0x8007      # Child added to selection
    EVENT_OBJECT_SELECTIONREMOVE   = 0x8008      # Child removed from selection
    EVENT_OBJECT_SELECTIONWITHIN   = 0x8009      # Multiple selection changes
    EVENT_OBJECT_STATECHANGE       = 0x800A      # Object's state changed
    EVENT_OBJECT_LOCATIONCHANGE    = 0x800B      # Object moved or resized
    EVENT_OBJECT_NAMECHANGE        = 0x800C      # Name property changed
    EVENT_OBJECT_DESCRIPTIONCHANGE = 0x800D      # Description property changed
    EVENT_OBJECT_VALUECHANGE       = 0x800E      # Value property changed
    EVENT_SYSTEM_ARRANGMENTPREVIEW = 0x8016      # Preview rectangle displayed
    EVENT_OBJECT_CONTENTSCROLLED   = 0x8015      # Scrolling ended on window object
    EVENT_OBJECT_HELPCHANGE        = 0x8010      # Help property changed
    EVENT_OBJECT_DEFACTIONCHANGE   = 0x8011      # DefaultAction property changed
    EVENT_OBJECT_ACCELERATORCHANGE = 0x8012      # KeyboardShortcut changed
    EVENT_OBJECT_TEXTEDIT_CONVERSIONTARGETCHANGED = 0x8030  # IME conversion target changed
    EVENT_OBJECT_TEXTSELECTIONCHANGED = 0x8014    # Text selection changed
    EVENT_OBJECT_INVOKED           = 0x8013      # Object invoked (e.g., button click)
    EVENT_OBJECT_LIVEREGIONCHANGED = 0x8019      # Live region object changed
    EVENT_OBJECT_UNCLOAKED         = 0x8018      # Window uncloaked (now visible)
    EVENT_OBJECT_CLOAKED           = 0x8017      # Window cloaked (invisible)
    EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED = 0x8020  # Hosted objects changed
    EVENT_OBJECT_DRAGSTART         = 0x8021      # Drag operation started
    EVENT_OBJECT_DRAGCANCEL        = 0x8022      # Drag operation canceled
    EVENT_OBJECT_DRAGCOMPLETE      = 0x8023      # Drag operation completed
    EVENT_OBJECT_DRAGENTER         = 0x8024      # Drag entered a drop target
    EVENT_OBJECT_DRAGLEAVE         = 0x8025      # Drag left a drop target
    EVENT_OBJECT_DRAGDROPPED       = 0x8026      # Drag dropped on target
    EVENT_OBJECT_IME_SHOW          = 0x8027      # IME window shown
    EVENT_OBJECT_IME_HIDE          = 0x8028      # IME window hidden
    EVENT_OBJECT_IME_CHANGE        = 0x8029      # IME window moved/resized
    EVENT_OBJECT_END               = 0x80FF      # Highest object event value

class WinEventFlags(IntEnum):
    """ Flags for WinEventProc. For more details see: https://learn.microsoft.com/en-gb/windows/win32/api/winuser/nf-winuser-setwineventhook """

    _SKIP_OWN_PROCESS	= 0x0002	# Avoids events generated by the same process.
    _SKIP_OWN_THREAD	= 0x0001	# Avoids events generated by the same thread.

    OUT_OF_CONTEXT   = 0x0000	# Callback runs outside the event-generating process (default behavior).
    IN_CONTEXT	    = 0x0004	# Callback runs inside the event-generating process (requires a DLL).

    SKIP_OWN_PROCESS_OUT_OF_CONTEXT = OUT_OF_CONTEXT | _SKIP_OWN_PROCESS
    SKIP_OWN_THREAD_OUT_OF_CONTEXT  = OUT_OF_CONTEXT | _SKIP_OWN_THREAD

    SKIP_OWN_PROCESS_IN_CONTEXT = IN_CONTEXT | _SKIP_OWN_PROCESS
    SKIP_OWN_THREAD_IN_CONTEXT  = IN_CONTEXT | _SKIP_OWN_THREAD

class WinEventMessages(IntEnum):
    """Windows Message codes. For more details see: https://pinvoke.net/default.aspx/Constants.WM"""

    WM_ACTIVATE             = 0x0006  # The WM_ACTIVATE message is sent when a window is being activated or deactivated.
    WM_ACTIVATEAPP          = 0x001C  # Sent when a window belonging to a different app is about to be activated/deactivated.
    WM_AFXFIRST             = 0x0360  # The first AFX (MFC) message.
    WM_AFXLAST              = 0x037F  # The last AFX (MFC) message.
    WM_APP                  = 0x8000  # Used by apps to define private messages (WM_APP + X).
    WM_ASKCBFORMATNAME      = 0x030C  # Clipboard viewer asks for name of an owner‐display format.
    WM_CANCELJOURNAL        = 0x004B  # Posted when user cancels journaling activities.
    WM_CANCELMODE           = 0x001F  # Cancel modes like mouse capture (e.g., when a dialog pops up).
    WM_CAPTURECHANGED       = 0x0215  # Sent to the window losing mouse capture.
    WM_CHANGECBCHAIN        = 0x030D  # Sent when a window is removed from the clipboard viewer chain.
    WM_CHANGEUISTATE        = 0x0127  # Indicates that the UI state should be changed.
    WM_CHAR                 = 0x0102  # Posted when TranslateMessage turns WM_KEYDOWN into a character.
    WM_CHARTOITEM           = 0x002F  # Listbox owner in response to WM_CHAR (with LBS_WANTKEYBOARDINPUT).
    WM_CHILDACTIVATE        = 0x0022  # Sent to a child when it’s activated (e.g., clicked or moved).
    WM_CLEAR                = 0x0303  # Delete (clear) current selection in edit/combo box.
    WM_CLOSE                = 0x0010  # Signal that a window/app should terminate.
    WM_COMMAND              = 0x0111  # Menus, controls, or accelerators send this.
    WM_COMPACTING           = 0x0041  # Sent when system memory is low (compacting).
    WM_COMPAREITEM          = 0x0039  # Determine sort position in owner‐drawn list/combobox.
    WM_CONTEXTMENU          = 0x007B  # Notifies a window of a right-click context menu.
    WM_COPY                 = 0x0301  # Copy current selection to clipboard (CF_TEXT).
    WM_COPYDATA             = 0x004A  # Pass data to another app.
    WM_CREATE               = 0x0001  # Sent when CreateWindow[Ex] is called (before it returns).
    WM_CTLCOLORBTN          = 0x0135  # Parent can set colors before drawing a button.
    WM_CTLCOLORDLG          = 0x0136  # Parent can set colors before drawing a dialog.
    WM_CTLCOLOREDIT         = 0x0133  # Parent can set colors for an edit control.
    WM_CTLCOLORLISTBOX      = 0x0134  # Parent can set colors for a listbox.
    WM_CTLCOLORMSGBOX       = 0x0132  # Parent can set colors for a message box.
    WM_CTLCOLORSCROLLBAR    = 0x0137  # Parent can set scrollbar background color.
    WM_CTLCOLORSTATIC       = 0x0138  # Parent sets colors for static or read-only edit.
    WM_CUT                  = 0x0300  # Cut current selection to clipboard (CF_TEXT).
    WM_DEADCHAR             = 0x0103  # Translated WM_KEYUP for dead keys (e.g., umlauts).
    WM_DELETEITEM           = 0x002D  # Sent when a listbox/combobox item is deleted.
    WM_DESTROY              = 0x0002  # Sent when a window is being destroyed.
    WM_DESTROYCLIPBOARD     = 0x0307  # Sent to clipboard owner when clipboard is emptied.
    WM_DEVICECHANGE         = 0x0219  # Hardware configuration change.
    WM_DEVMODECHANGE        = 0x001B  # Sent when device-mode settings change.
    WM_DISPLAYCHANGE        = 0x007E  # Display resolution changed.
    WM_DRAWCLIPBOARD        = 0x0308  # Clipboard content changed (clipboard viewer chain).
    WM_DRAWITEM             = 0x002B  # Visual aspect of owner-drawn control/menu changed.
    WM_DROPFILES            = 0x0233  # File dropped on app window (drag-and-drop).
    WM_ENABLE               = 0x000A  # Window’s enabled state changed.
    WM_ENDSESSION           = 0x0016  # After WM_QUERYENDSESSION, tells if session is ending.
    WM_ENTERIDLE            = 0x0121  # Owner of modal dialog/menu entering idle.
    WM_ENTERMENULOOP        = 0x0211  # Menu modal loop entered.
    WM_ENTERSIZEMOVE        = 0x0231  # Started moving/resizing loop.
    WM_ERASEBKGND           = 0x0014  # Background must be erased (e.g., resize).
    WM_EXITMENULOOP         = 0x0212  # Menu modal loop exited.
    WM_EXITSIZEMOVE         = 0x0232  # Finished moving/resizing loop.
    WM_FONTCHANGE           = 0x001D  # Font pool changed.
    WM_GETDLGCODE           = 0x0087  # Control overrides default dialog key handling.
    WM_GETFONT              = 0x0031  # Retrieve control’s current font.
    WM_GETHOTKEY            = 0x0033  # Determine window’s hotkey.
    WM_GETICON              = 0x007F  # Retrieve handle to window’s icon.
    WM_GETMINMAXINFO        = 0x0024  # Override max/min tracking sizes.
    WM_GETOBJECT            = 0x003D  # Active Accessibility requests object info.
    WM_GETTEXT              = 0x000D  # Copy window text into buffer.
    WM_GETTEXTLENGTH        = 0x000E  # Get length of window’s text.
    WM_HANDHELDFIRST        = 0x0358  # [Definition needed]
    WM_HANDHELDLAST         = 0x035F  # [Definition needed]
    WM_HELP                 = 0x0053  # F1 pressed (help).
    WM_HOTKEY               = 0x0312  # Registered hotkey pressed.
    WM_HSCROLL              = 0x0114  # Horizontal scroll event.
    WM_HSCROLLCLIPBOARD     = 0x030E  # Clipboard viewer’s h-scroll.
    WM_ICONERASEBKGND       = 0x0027  # Erase background of minimized icon.
    WM_IME_CHAR             = 0x0286  # IME composition character.
    WM_IME_COMPOSITION      = 0x010F  # IME composition status changed.
    WM_IME_COMPOSITIONFULL  = 0x0284  # IME composition window is full.
    WM_IME_CONTROL          = 0x0283  # Direct IME commands.
    WM_IME_ENDCOMPOSITION   = 0x010E  # IME composition ended.
    WM_IME_KEYDOWN          = 0x0290  # IME key press.
    WM_IME_KEYLAST          = 0x010F  # [Definition needed]
    WM_IME_KEYUP            = 0x0291  # IME key release.
    WM_IME_NOTIFY           = 0x0282  # IME window events.
    WM_IME_REQUEST          = 0x0288  # IME commands/info requests.
    WM_IME_SELECT           = 0x0285  # IME selection change.
    WM_IME_SETCONTEXT       = 0x0281  # IME context set on activation.
    WM_IME_STARTCOMPOSITION = 0x010D  # IME starting composition.
    WM_INITDIALOG           = 0x0110  # Dialog box initialization.
    WM_INITMENU             = 0x0116  # Menu about to become active.
    WM_INITMENUPOPUP        = 0x0117  # Submenu about to pop up.
    WM_INPUTLANGCHANGE      = 0x0051  # Input language changed.
    WM_INPUTLANGCHANGEREQUEST = 0x0050  # Input language change requested.
    WM_KEYDOWN              = 0x0100  # Nonsystem key pressed.
    WM_KEYFIRST             = 0x0100  # First keyboard message.
    WM_KEYLAST              = 0x0108  # Last keyboard message.
    WM_KEYUP                = 0x0101  # Nonsystem key released.
    WM_KILLFOCUS            = 0x0008  # Window losing keyboard focus.
    WM_LBUTTONDBLCLK        = 0x0203  # Left-button double-click.
    WM_LBUTTONDOWN          = 0x0201  # Left-button down.
    WM_LBUTTONUP            = 0x0202  # Left-button up.
    WM_MBUTTONDBLCLK        = 0x0209  # Middle-button double-click.
    WM_MBUTTONDOWN          = 0x0207  # Middle-button down.
    WM_MBUTTONUP            = 0x0208  # Middle-button up.
    WM_MDIACTIVATE          = 0x0222  # MDI child activation.
    WM_MDICASCADE           = 0x0227  # Cascade MDI children.
    WM_MDICREATE            = 0x0220  # Create MDI child.
    WM_MDIDESTROY           = 0x0221  # Destroy MDI child.
    WM_MDIGETACTIVE         = 0x0229  # Get active MDI child.
    WM_MDIICONARRANGE       = 0x0228  # Arrange MDI icons.
    WM_MDIMAXIMIZE          = 0x0225  # Maximize MDI child.
    WM_MDINEXT              = 0x0224  # Activate next/prev MDI child.
    WM_MDIREFRESHMENU       = 0x0234  # Refresh MDI menu.
    WM_MDIRESTORE           = 0x0223  # Restore MDI child.
    WM_MDISETMENU           = 0x0230  # Set MDI frame/menu.
    WM_MDITILE              = 0x0226  # Tile MDI children.
    WM_MEASUREITEM          = 0x002C  # Control/menu measure item.
    WM_MENUCHAR             = 0x0120  # Unmatched menu key pressed.
    WM_MENUCOMMAND          = 0x0126  # Menu selection command.
    WM_MENUDRAG             = 0x0123  # Drag-and-drop in menus.
    WM_MENUGETOBJECT        = 0x0124  # Hit-test in drag-and-drop menu.
    WM_MENURBUTTONUP        = 0x0122  # Right-click release on menu.
    WM_MENUSELECT           = 0x011F  # Menu item selected.
    WM_MOUSEACTIVATE        = 0x0021  # Click in inactive window.
    WM_MOUSEFIRST           = 0x0200  # First mouse message (use Peek).
    WM_MOUSEHOVER           = 0x02A1  # Mouse hover.
    WM_MOUSELAST            = 0x020D  # Last mouse message.
    WM_MOUSELEAVE           = 0x02A3  # Mouse leave.
    WM_MOUSEMOVE            = 0x0200  # Mouse move.
    WM_MOUSEWHEEL           = 0x020A  # Mouse wheel rotated.
    WM_MOUSEHWHEEL          = 0x020E  # Horizontal wheel rotated.
    WM_MOVE                 = 0x0003  # Window moved.
    WM_MOVING               = 0x0216  # User moving window.
    WM_NCACTIVATE           = 0x0086  # Non‐client area activation.
    WM_NCCALCSIZE           = 0x0083  # Calculate client area size.
    WM_NCCREATE             = 0x0081  # Non‐client area creation.
    WM_NCDESTROY            = 0x0082  # Non‐client area destroy.
    WM_NCHITTEST            = 0x0084  # Hit‐test in non‐client area.
    WM_NCLBUTTONDBLCLK      = 0x00A3  # Double‐click in non‐client area.
    WM_NCLBUTTONDOWN        = 0x00A1  # Button down in non‐client area.
    WM_NCLBUTTONUP          = 0x00A2  # Button up in non‐client area.
    WM_NCMBUTTONDBLCLK      = 0x00A9  # Middle dblclk non‐client.
    WM_NCMBUTTONDOWN        = 0x00A7  # Middle down non‐client.
    WM_NCMBUTTONUP          = 0x00A8  # Middle up non‐client.
    WM_NCMOUSEHOVER         = 0x02A0  # Hover in non‐client area.
    WM_NCMOUSELEAVE         = 0x02A2  # Leave non‐client area.
    WM_NCMOUSEMOVE          = 0x00A0  # Mouse move non‐client.
    WM_NCPAINT              = 0x0085  # Paint non‐client area.
    WM_NCRBUTTONDBLCLK      = 0x00A6  # Right dblclk non‐client.
    WM_NCRBUTTONDOWN        = 0x00A4  # Right down non‐client.
    WM_NCRBUTTONUP          = 0x00A5  # Right up non‐client.
    WM_NCXBUTTONDBLCLK      = 0x00AD  # X button dblclk non‐client.
    WM_NCXBUTTONDOWN        = 0x00AB  # X button down non‐client.
    WM_NCXBUTTONUP          = 0x00AC  # X button up non‐client.
    WM_NCUAHDRAWCAPTION     = 0x00AE  # Undocumented themes draw caption.
    WM_NCUAHDRAWFRAME       = 0x00AF  # Undocumented themes draw frame.
    WM_NEXTDLGCTL           = 0x0028  # Change focus in dialog.
    WM_NEXTMENU             = 0x0213  # Switch menu bar/system menu.
    WM_NOTIFY               = 0x004E  # Common control notifications.
    WM_NOTIFYFORMAT         = 0x0055  # ANSI vs Unicode in WM_NOTIFY.
    WM_NULL                 = 0x0000  # Does nothing.
    WM_PAINT                = 0x000F  # Needs repaint.
    WM_PAINTCLIPBOARD       = 0x0309  # Clipboard viewer needs repaint.
    WM_PAINTICON            = 0x0026  # Paint icon background (old Win).
    WM_PALETTECHANGED       = 0x0311  # Logical palette realized.
    WM_PALETTEISCHANGING    = 0x0310  # App is about to realize palette.
    WM_PARENTNOTIFY         = 0x0210  # Child created/destroyed or click.
    WM_PASTE                = 0x0302  # Paste CF_TEXT from clipboard.
    WM_PENWINFIRST          = 0x0380  # [Definition needed]
    WM_PENWINLAST           = 0x038F  # [Definition needed]
    WM_POWER                = 0x0048  # Battery‐powered suspend (old).
    WM_POWERBROADCAST       = 0x0218  # Power‐management event.
    WM_PRINT                = 0x0317  # Request window draw (e.g., printer).
    WM_PRINTCLIENT          = 0x0318  # Request client area draw.
    WM_QUERYDRAGICON        = 0x0037  # About to drag minimized icon.
    WM_QUERYENDSESSION      = 0x0011  # Query before session end.
    WM_QUERYNEWPALETTE      = 0x030F  # About to get keyboard focus—palette.
    WM_QUERYOPEN            = 0x0013  # Icon about to be restored.
    WM_QUEUESYNC            = 0x0023  # Separate CBT from user‐input.
    WM_QUIT                 = 0x0012  # Ends the message loop.
    WM_RBUTTONDBLCLK        = 0x0206  # Right-button double-click.
    WM_RBUTTONDOWN          = 0x0204  # Right-button down.
    WM_RBUTTONUP            = 0x0205  # Right-button up.
    WM_RENDERALLFORMATS     = 0x0306  # Render all delayed clipboard formats.
    WM_RENDERFORMAT         = 0x0305  # Render one delayed clipboard format.
    WM_SETCURSOR            = 0x0020  # Cursor move within window.
    WM_SETFOCUS             = 0x0007  # Window gets keyboard focus.
    WM_SETFONT              = 0x0030  # Set control’s font.
    WM_SETHOTKEY            = 0x0032  # Associate hotkey with window.
    WM_SETICON              = 0x0080  # Set window icon.
    WM_SETREDRAW            = 0x000B  # Allow/prevent redraw.
    WM_SETTEXT              = 0x000C  # Change window text.
    WM_SETTINGCHANGE        = 0x001A  # WIN.INI settings changed.
    WM_SHOWWINDOW           = 0x0018  # Window about to be shown/hidden.
    WM_SIZE                 = 0x0005  # Window size changed.
    WM_SIZECLIPBOARD        = 0x030B  # Clipboard viewer area resized.
    WM_SIZING               = 0x0214  # User resizing window.
    WM_SPOOLERSTATUS        = 0x002A  # Print queue changed.
    WM_STYLECHANGED         = 0x007D  # Window style changed.
    WM_STYLECHANGING        = 0x007C  # Window style about to change.
    WM_SYNCPAINT            = 0x0088  # Sync painting across threads.
    WM_SYSCHAR              = 0x0106  # TranslateMessage of WM_SYSKEYDOWN.
    WM_SYSCOLORCHANGE       = 0x0015  # System color setting changed.
    WM_SYSCOMMAND           = 0x0112  # System menu/maximize/minimize/close.
    WM_SYSDEADCHAR          = 0x0107  # System dead‐key char.
    WM_SYSKEYDOWN           = 0x0104  # System key down (ALT+key or F10).
    WM_SYSKEYUP             = 0x0105  # System key up.
    WM_TCARD                = 0x0052  # Training card button clicked.
    WM_TIMECHANGE           = 0x001E  # System time changed.
    WM_TIMER                = 0x0113  # Timer expired.
    WM_UNDO                 = 0x0304  # Undo last edit operation.
    WM_UNINITMENUPOPUP      = 0x0125  # Submenu destroyed.
    WM_USER                 = 0x0400  # Base for app-defined messages.
    WM_USERCHANGED          = 0x0054  # User logon/logoff settings updated.
    WM_VKEYTOITEM           = 0x002E  # Listbox responds to WM_KEYDOWN.
    WM_VSCROLL              = 0x0115  # Vertical scroll event.
    WM_VSCROLLCLIPBOARD     = 0x030A  # Clipboard viewer’s v-scroll.
    WM_WINDOWPOSCHANGED     = 0x0047  # Window position or Z‐order changed.
    WM_WINDOWPOSCHANGING    = 0x0046  # Window position about to change.
    WM_WININICHANGE         = 0x001A  # Compatibility alias for WM_SETTINGCHANGE.
    WM_XBUTTONDBLCLK        = 0x020D  # X button dblclk.
    WM_XBUTTONDOWN          = 0x020B  # X button down.
    WM_XBUTTONUP            = 0x020C  # X button up.

class WinObjectIdentifiers(IntEnum): 
    OBJID_WINDOW    = 0x00000000	
    OBJID_SYSMENU	= 0xFFFFFFFF	
    OBJID_TITLEBAR	= 0xFFFFFFFE	
    OBJID_MENU	    = 0xFFFFFFFD	
    OBJID_CLIENT	= 0xFFFFFFFC	
    OBJID_VSCROLL	= 0xFFFFFFFB	
    OBJID_HSCROLL	= 0xFFFFFFFA	
    OBJID_SIZEGRIP	= 0xFFFFFFF9
    OBJID_CARET	    = 0xFFFFFFF8
    OBJID_CURSOR	= 0xFFFFFFF7
    OBJID_ALERT	    = 0xFFFFFFF6
    OBJID_SOUND	    = 0xFFFFFFF5
    OBJID_QUERYCLASSNAMEIDX = 0xFFFFFFF4
    OBJID_NATIVEOM	= 0xFFFFFFF0