# IMPORTANT: 
# After changing the config.toml file, you need to restart 
# the script for the changes to take effect.


# Special Key Bindings:
#   alt
#   ctrl
#   shift
#   left alt
#   left ctrl
#   left shift
#   right alt
#   right ctrl
#   right shift
#   alt gr

#   windows key does *NOT* work


[general]
title = 'Custom Hotkeys'
workspace_ignores_pinned = [1,2,4,5,6,7,8,9] # Sets which workspaces ignore pinned windows as open for default programs

[hotkeys]
open_web_tab = 'ctrl+space'
pin_current_window_toggle = 'alt+l'         # makes window visible on each workspace
goto_previous_program = 'alt gr+z'
goto_previous_workspace = 'alt+0'
move_program_to_workspace = 'alt+space'     # 'goto_workpace_x' is appened as shortcut for workspace
goto_workspace_with_program = 'alt+space+0' # 'goto_workpace_x' is appened as shortcut for workspace

# Only specific app_ids are valid.
# To get app_ids start the script and search for your programm in the newly generated "app_data.json"
[applications]
web_browser = 'MSEdge'

[workspace_shortcuts]
modifiers = 'alt'
goto_workpace_1 = '1'
goto_workpace_2 = '2'
goto_workpace_3 = '3'
goto_workpace_4 = '4'
goto_workpace_5 = '5'
goto_workpace_6 = '6'
goto_workpace_7 = '7'
goto_workpace_8 = '8'
goto_workpace_9 = '9'


# Add application key from [applications] if you want a workspace 
# to open the specified application if not open already.
[workspace_programs]
workspace_1_open = 'web_browser'
workspace_2_open = false
workspace_3_open = false
workspace_4_open = false
workspace_6_open = false
workspace_5_open = false
workspace_7_open = false
workspace_8_open = false
workspace_9_open = false

[workspace_names]
workspace_1_name = 'Web browsing'
workspace_2_name = 'Programming 1'
workspace_3_name = 'Programming 2'
workspace_4_name = 'Programming 3'
workspace_5_name = 'Workspace 5'
workspace_6_name = 'Workspace 6'
workspace_7_name = 'Workspace 7'
workspace_8_name = 'Workspace 8'
workspace_9_name = 'Workspace 9'