# IMPORTANT: 
# The after changing the config.toml file, you need to restart 
# the script for the changes to take effect.

# If you dont want or need a hotkey, you can just delete the
# line from the hotkeys section.

[general]
title = 'Custom Hotkeys'

[hotkeys]
focus_web_browser = '<alt>+t'
open_web_tab = '<ctrl>+<space>'
goto_previous = '<cmd>+z'

[applications]
web_browser = 'edge'


# Special Key Bindings:
# <ctrl>        : Control key
# <alt>         : Alt key
# <shift>       : Shift key
# <cmd>         : Windows key
# <alt_gr>      : AltGr key
# <caps_lock>   : Caps Lock key
# <tab>         : Tab key
# <esc>         : Escape key
# <enter>       : Enter/Return key
# <space>       : Spacebar
# <backspace>   : Backspace key
# <delete>      : Delete key
# <insert>      : Insert key
# <home>        : Home key
# <end>         : End key
# <page_up>     : Page Up key
# <page_down>   : Page Down key
# <left>        : Arrow left
# <right>       : Arrow right
# <up>          : Arrow up
# <down>        : Arrow down
# <f1> - <f20>  : Function keys F1 - F20